// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYINIDykTbeH3n8Jg9p287Zi-JL1hpO8',
    appId: '1:1052612162492:web:81727d9ca82073df32b1b9',
    messagingSenderId: '1052612162492',
    projectId: 'maatha-7193c',
    authDomain: 'maatha-7193c.firebaseapp.com',
    storageBucket: 'maatha-7193c.firebasestorage.app',
    measurementId: 'G-J2K2ZMY9EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBta3wfOmm2sv8Aja0OynnODJijugu3AVI',
    appId: '1:1052612162492:android:75f8ce2374ebd50932b1b9',
    messagingSenderId: '1052612162492',
    projectId: 'maatha-7193c',
    storageBucket: 'maatha-7193c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKkD22Sbc0dO_KhZ4ZTgiDf489iPWQGA',
    appId: '1:1052612162492:ios:192a4962386def0532b1b9',
    messagingSenderId: '1052612162492',
    projectId: 'maatha-7193c',
    storageBucket: 'maatha-7193c.firebasestorage.app',
    iosBundleId: 'com.example.mathaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKkD22Sbc0dO_KhZ4ZTgiDf489iPWQGA',
    appId: '1:1052612162492:ios:192a4962386def0532b1b9',
    messagingSenderId: '1052612162492',
    projectId: 'maatha-7193c',
    storageBucket: 'maatha-7193c.firebasestorage.app',
    iosBundleId: 'com.example.mathaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTYINIDykTbeH3n8Jg9p287Zi-JL1hpO8',
    appId: '1:1052612162492:web:9b081bdca6e7782f32b1b9',
    messagingSenderId: '1052612162492',
    projectId: 'maatha-7193c',
    authDomain: 'maatha-7193c.firebaseapp.com',
    storageBucket: 'maatha-7193c.firebasestorage.app',
    measurementId: 'G-4CQY5GRXMR',
  );

}